### ISSUE TITLE
No negative Values

### ISSUE THREAD

**Issue by chrismin13** [haselkern/Minecraft-ArmorStand#10]
Positions can take negative values in Minecraft. This is very important if you want to move an arm forwards or something along those lines. Please add negative values!

**Comment by haselkern** [comment]
I'm not sure if I understand your issue correctly, but as it is right now, rotations between 0° and 360° are perfectly fine. If you want to rotate something by -90° you can set the slider to 270° to get the same effect.

**Comment by chrismin13** [comment]
OH WOW. I'm stupid. Sorry dude, I wasted your time. You've made an epic
utility! Sorry, I'll turn on my brain next time around...
