### ISSUE TITLE
unable to summon subject

### ISSUE THREAD

**Issue by creeerik** [haselkern/Minecraft-ArmorStand#13]
hi 
i have my own server and i want some cool armouwstands.
but when i put the command in a commandblock but it says unalbe to summon subject
![2017-06-09_16 10 06](https://user-images.githubusercontent.com/27501101/26979162-2f70cff4-4d2e-11e7-838b-fc893fb9d3d9.png)
i have a spitgot server in 1.8 client forge 1.8

**Comment by chrismin13** [comment]
The armor stand name changed between 1 10 and 1.11, so you'll have to find what the Armor Stand is called on 1.8 and change it to that.
However, I'd recommend that you install the plugin Armor Stand Tools as it allows you to easily create and edit armorstands on the fly.

**Comment by chrismin13** [comment]
Forget that actually, it has an option at the top of the page. Change it to Minecraft 1.8 instead of Minecraft 1.11.

**Comment by haselkern** [comment]
Yup, @chrismin13 is right 👍

**Comment by creeerik** [comment]
Ah now it is doing right thx, I didn't see it before
