### ISSUE TITLE
Minor detail

### ISSUE THREAD

**Issue by FlameVapour** [haselkern/Minecraft-ArmorStand#15]
In 1.12.2 (and possibly 1.12 and 1.11) you can type 256 characters instead of 100, meaning you don't need a command block unless you have every option checked.

**Comment by haselkern** [comment]
That's interesting, thanks for the heads up 👍 I will look into that later.

**Comment by haselkern** [comment]
Fixed in b70c469ecd8645d5eddd6d795d49ea53bcd614e5
