### ISSUE TITLE
clicking on minecraft version for armor stand does not work

### ISSUE THREAD

**Issue by GarchompGirl** [haselkern/Minecraft-ArmorStand#18]
ok so i needed a armorstand but im in minecraft 1.10.2 and when i click on the Minecraft 1.13 and above it just gives me a lagspike and does nothing

**Comment by haselkern** [comment]
Can you press <kbd>F12</kbd> to open the developer tools, before pressing the button? In the console tab, there should be some sort of error message appeearing.
