### ISSUE TITLE
Saving and loading

### ISSUE THREAD

**Issue by haselkern** [haselkern/Minecraft-ArmorStand#20]
I got a suggestions that it would be nice to save and load armorstands. That's a fantastic idea and it should be implemented some day.

**Comment by thelennylord** [comment]
That's an interesting idea, just wondering will it be saved to a database where users can see each other's creations or is going to be saved locally just for that user?

**Comment by haselkern** [comment]
Sharing the armorstands somehow would be really cool, but since this project is client side only, the armorstands would probably be saved in the clients localstorage.

**Comment by haselkern** [comment]
Solved by #23
