### ISSUE TITLE
Website not working

### ISSUE THREAD

**Issue by thelennylord** [haselkern/Minecraft-ArmorStand#21]
The website ( https://haselkern.com/Minecraft-ArmorStand/ ) doesn't seem to be working. It gives me the error ERR_CONNECTION_REFUSED. However, connecting via https://haselkern.github.io/Minecraft-ArmorStand/ seems to be working. I have been facing this since 2 days and waited it out thinking the issue was on my end but it seems it isn't on my end as one of my friends were unable to connect to it.

**Comment by haselkern** [comment]
Hi! haselkern.com is on my own dedicated server, haselkern.github.io is hosted on GitHub. My webhost had some technical issues with their servers, but those were (hopefully) resolved and should not happen again.

Sorry for any inconvenience!
