### ISSUE TITLE
custom Items doesnt work with this code

### ISSUE THREAD

**Issue by MystVil78** [haselkern/Minecraft-ArmorStand#26]
I tried to put a green dyed leather chestplate ( ID: minecraft:leather_chestplate{display:{color:3491355}} ) on the armor stand but it didnt worked. Another time i tried to put an enchanted Bow ( ID:minecraft:bow{ench:[{}]} ) on the armor stand and it didnt worked too. I checked the code myself but I didnt found something.

**Comment by thelennylord** [comment]
The IDs you've given are only meant to work on the give (or equivalent) commands. If you want the armour stand to hold items with custom NBTs then you'll have to put those in the `tag` key. 

However, the website doesn't support custom items yet, but you can select colours for any leather armour piece on the website by selecting it as the equipment and a colour picker should appear next to it.

**Comment by MystVil78** [comment]
Ok ill try this. Thank you!
