### ISSUE TITLE
Website not working

### ISSUE THREAD

**Issue by cameracameraboo23** [haselkern/Minecraft-ArmorStand#27]
The armour stand on the left is not showing up (even though I have WebGL) and the command is not appearing. I have enabled javascript and updated my mac but it is still not working.

**Comment by cameracameraboo23** [comment]
Google chrome.

**Comment by haselkern** [comment]
That's even weirder! I unfortunately have no Mac on my hands to test this, but it works on Chrome for Linux. Could you press <kbd>Command</kbd>+<kbd>Option</kbd>+<kbd>J</kbd> to bring up the developer console and then reload the page? Please send me any errors that pop up.

**Comment by cameracameraboo23** [comment]
Ah I found the problem - Privacy Badger was blocking it.
