### ISSUE TITLE
Player head equipment not generating command

### ISSUE THREAD

**Issue by rgnter** [haselkern/Minecraft-ArmorStand#29]
Hello, I have noticed that putting any kind of Player Head (Player name, Texture URL, Give code) does not generate command. _Tested this on multiple machines with same results._ 
> ![image](https://user-images.githubusercontent.com/32541639/97595804-5862e680-1a04-11eb-9331-74d879aee3f7.png)
Command version 1.16, Armor stand version 1.16. 

Cheers.

**Comment by rgnter** [comment]
Further observation: Works for Armor stand version 1.13 and below.

**Comment by thelennylord** [comment]
Whoops, seems like I've forgotten to update the give code's version check to support versions 1.14 and above. Fortunately, the fix is simple; just have to edit 2 lines.

I'll make a PR implementing a fix for this issue soon as I'm currently busy right now.
