### ISSUE TITLE
Small isn't showing as small

### ISSUE THREAD

**Issue by TheMaxShaft** [haselkern/Minecraft-ArmorStand#3]
Small armor stands on safari aren't showing up as small

(PS. Can you add a custom head equipment feature)

**Comment by haselkern** [comment]
Well, they were not intended to show up as small, but that is a cool feature which I will quickly implement.

If I did understand you correctly, there is custom head equipment available, it just doesn't render it. Below the sliders there is the category ```Use Custom Equipment``` which you might want to check out.

**Comment by TheMaxShaft** [comment]
i meant by that the custom heads, heads from heads.freshcoal or http://www.dragnoz.com/custom-head-block-generator/

**Comment by haselkern** [comment]
Ohhh, ok. Give me some time, but that shouldn't be too hard to create. Thanks again!

**Comment by haselkern** [comment]
Implemented in commit 0a1a092233f4a5ce6ae9f224099cf6028e3a3b16
