### ISSUE TITLE
Image URL to Custom Head didnt work

### ISSUE THREAD

**Issue by barraIhsan** [haselkern/Minecraft-ArmorStand#32]
This is what i got from Image to URL (And i only take the player head part)
`give @p player_head{SkullOwner:{Id:2998780d-cad1-40dc-89a0-a042d6adc6f3,Properties:{textures:[{Value:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTVhYThjM2E5MWQzMjVkNDVmYzUzODY3NjY3ZWY5ZDRlNzQ1NWQyY2ZlZGU0YjA1NjA3ZTZkYWY2ODYwZTdkNSJ9fX0=}]}}`

As supposed to be
`give @p player_head{SkullOwner:{Id:[I;697858061,-892256036,-1985961918,-693254413],Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTVhYThjM2E5MWQzMjVkNDVmYzUzODY3NjY3ZWY5ZDRlNzQ1NWQyY2ZlZGU0YjA1NjA3ZTZkYWY2ODYwZTdkNSJ9fX0="}]}}}`

**The different**
You should put "" in value
You should convert the old UUID, to int array => https://www.soltoder.com/mc-uuid-converter/ (For the "Id:")

**Comment by thelennylord** [comment]
Interesting, I wasn't aware of the change in UUID representation in 1.16. 

I'll implement a fix for this soon.
