### ISSUE TITLE
Arm rotataion seems to be reversed

### ISSUE THREAD

**Issue by TheMaxShaft** [haselkern/Minecraft-ArmorStand#4]
When i have the posture set to this: 
![screen shot 2015-03-21 at 10 43 10 pm](https://cloud.githubusercontent.com/assets/10644674/6767755/bb5b0c10-d01b-11e4-86ad-28a9b92e72d9.png)
It appears in minecraft as this:
![2015-03-21_22 43 29](https://cloud.githubusercontent.com/assets/10644674/6767759/cdd2074a-d01b-11e4-964d-e56f1fe97607.png)

(Ps. I came up with a new idea: Leather armor dying GUI (RGB Codes and stuff))

**Comment by WheezyGold7931** [comment]
Make sure to use Google Chrome

**Comment by WheezyGold7931** [comment]
And nice idea

**Comment by haselkern** [comment]
Well, that is indeed an issue that I have no idea how to fix. But a method to prevent this behavior is to only modify two sliders for each limb. Leaving one at zero usually works.  
I know that this isn't great, but I couldn't find a solution. If you know someone who can fix this, *please* contact them somehow.  
I might add the dying thing, sounds good.

**Comment by TheMaxShaft** [comment]
how about trying to have the arms rotate in reverse of what they normally do. same positioning, different display (it may work)

**Comment by haselkern** [comment]
During a tedious process I already tried negating all rotation values. But that is not the problem. I think there is something wrong with the way THREE.js handles rotations versus the way Minecraft handles it. Feel free to fork this project and create a working solution, or something that comes close to Minecraft way to handle that.

**Comment by stefnotch** [comment]
Just asking, what were the rotation values?

**Comment by haselkern** [comment]
Yeah, I finally made it work :tada:
5c466e71d2a3faecea777e0f25ef58f7ff5770f4
