### ISSUE TITLE
Add login [Request]

### ISSUE THREAD

**Issue by xhendrikg** [haselkern/Minecraft-ArmorStand#40]
Maybe add something where you can 

- [ ] login and 

- [ ] save command and share on the website with all people (like mcstacker)

**Comment by thelennylord** [comment]
It would be really cool if you were able to share your creations with the community and use their creations too, but this project is currently purely client-sided and we have no plans to implement a server-side logic for it.

You can still save your creations locally and load them back whenever needed.

**Comment by xhendrikg** [comment]
> It would be really cool if you were able to share your creations with the community and use their creations too, but this project is currently purely client-sided and we have no plans to implement a server-side logic for it.
> 
> 
> 
> You can still save your creations locally and load them back whenever needed.

Are there saved when I'm in igoknito or restart my pc?

**Comment by thelennylord** [comment]
> Are there saved when I'm in igoknito or restart my pc?

Your creations are saved on your browser's local storage, so it should be saved even if you restart your PC. However, incognito mode deletes your local storage after a session ends, so it won't save. If you want them to be saved then don't use incognito mode while saving.

**Comment by xhendrikg** [comment]
> > Are there saved when I'm in igoknito or restart my pc?
> 
> 
> 
> Your creations are saved on your browser's local storage, so it should be saved even if you restart your PC. However, incognito mode deletes your local storage after a session ends, so it won't save. If you want them to be saved then don't use incognito mode while saving.
> 
> 
> 
> 

So you mean cookies?

**Comment by thelennylord** [comment]
> > > Are there saved when I'm in igoknito or restart my pc?
> > 
> > 
> > Your creations are saved on your browser's local storage, so it should be saved even if you restart your PC. However, incognito mode deletes your local storage after a session ends, so it won't save. If you want them to be saved then don't use incognito mode while saving.
> 
> So you mean cookies?

No, cookies are not the same as local storage. You can read more about local storages [here.](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage)
