### ISSUE TITLE
Png

### ISSUE THREAD

**Issue by MinecraftVR** [haselkern/Minecraft-ArmorStand#41]
The PNG URL for the armor stand isnt working

**Comment by haselkern** [comment]
Could you be a bit more specific? The [official website](https://haselkern.com/Minecraft-ArmorStand/) works fine for me, all resources are loading properly. There are some modded forks of this tool flying around, which might be broken, but I cannot influence them.

**Comment by haselkern** [comment]
Since everything seems to be working fine I will close this issue. If the problem persists, please explain your problem further and reopen the issue.
