### ISSUE TITLE
Invulnerable Issue

### ISSUE THREAD

**Issue by MrCake21** [haselkern/Minecraft-ArmorStand#44]
I'm unsure for what versions it does not work but if you give any armor stand the "Invulnerable" tag does nothing, all I know is that it doesn't work for 1.19+ so I'd suggest to remove that option but I'm unsure. (Also, when you make armor stands invisible it also makes them indestructible so I'd probably state that somewhere, thanks!)

**Comment by thelennylord** [comment]
An armor stand with an Invulnerable tag cannot be destroyed by players in survival or adventure mode. However, you can break them in creative mode.

Also, armor stands with the Invisible tag becoming invisible and indestructible is an intentional behaviour.

**Comment by MrCake21** [comment]
Thank you! I was also wondering, is there a way to make an armor stand bigger, or a way so that when playing in survival / adventure you can't take armor or items off an armor stand?

**Comment by thelennylord** [comment]
> is there a way to make an armor stand bigger

No, there's no way to make an armor stand bigger.

>  a way so that when playing in survival / adventure you can't take armor or items off an armor stand?

Enable "Lock Slot Interaction" (should be above the code output), and then select which slots you would like to be disabled.
