### ISSUE TITLE
Add a "NOT AN OFFICIAL MINECRAFT PRODUCT" disclaimer.

### ISSUE THREAD

**Issue by bauerbach** [haselkern/Minecraft-ArmorStand#48]
The Minecraft EULA was recently updated and now requires a disclaimer (among other things). The relavent part is below:

"Prominently include the disclaimer similar to the following: “NOT AN OFFICIAL MINECRAFT [PRODUCT/SERVICE/EVENT/etc.]. NOT APPROVED BY OR ASSOCIATED WITH MOJANG OR MICROSOFT” on your product, listing, description, website/webpage, and all other related materials."

It would be strongly recommended to add such a disclaimer!

**Comment by haselkern** [comment]
Hi! Thanks for the heads up, do you have a source I can look into? On https://www.minecraft.net/en-us/eula they say:

> You may develop tools, plug-ins and services as long as they do not seem official or approved by us, such as by using our logos.

I don't think this tool seems official, so I would think I'm good.
