### ISSUE TITLE
Right leg is written in the command as "RightLeft"

### ISSUE THREAD

**Issue by chronoppo** [haselkern/Minecraft-ArmorStand#51]
I apologize if this isnt the correct place to put this, it was all I could find. Basically what the title says, Right Leg is translated to the command as "RightLeft". 
![image](https://github.com/user-attachments/assets/81c5f0bb-8251-4dc7-8366-e91872672a4f)

**Comment by haselkern** [comment]
This is exactly the right place to report this! Thanks for pointing it out, I fixed it in db098a3.
