### ISSUE TITLE
Configuration issues in version 1.8

### ISSUE THREAD

**Issue by SABANUSI** [haselkern/Minecraft-ArmorStand#52]
When setting up the armor stand in version 1.8, even if I turned “Enable Equipment” on, the armor settings were not reflected in the commands.
Since it was working properly in versions 1.9 and later,
I would like you to fix it so that it works properly in version 1.8 as well.

(I'm using a translation tool, sorry!)

![image](https://github.com/user-attachments/assets/e875c32c-3ef3-4c2d-8b38-e1b6f9fd0a15)

**Comment by haselkern** [comment]
Hi! Your translation tool works really well, no worries :)

I fixed the issue in 6413875.

Feel free to reopen this issue if there are any problems!
